//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_project_ver_5.DB_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demo_ver5Entities : DbContext
    {
        private static demo_ver5Entities _context;
        public demo_ver5Entities()
            : base("name=demo_ver5Entities")
        {
        }
        public static demo_ver5Entities GetContext()
        {
            if (_context == null)
                _context = new demo_ver5Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TbЗаказ> TbЗаказ { get; set; }
        public virtual DbSet<TbКатегории> TbКатегории { get; set; }
        public virtual DbSet<TbПользователь> TbПользователь { get; set; }
        public virtual DbSet<TbСтатус> TbСтатус { get; set; }
        public virtual DbSet<TbСтрокиЗаказа> TbСтрокиЗаказа { get; set; }
        public virtual DbSet<TbТовары> TbТовары { get; set; }
    }
}
