//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_project_ver_5.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbЗаказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbЗаказ()
        {
            this.TbСтрокиЗаказа = new HashSet<TbСтрокиЗаказа>();
        }
    
        public int Код_заказа { get; set; }
        public int Количество { get; set; }
        public int Код_пользователя { get; set; }
        public int Статус { get; set; }
    
        public virtual TbПользователь TbПользователь { get; set; }
        public virtual TbСтатус TbСтатус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbСтрокиЗаказа> TbСтрокиЗаказа { get; set; }
    }
}
