//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_project_ver_5.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbСтрокиЗаказа
    {
        public int Код_заказа_строки { get; set; }
        public int Код_Товара { get; set; }
        public int Код_Заказа { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual TbЗаказ TbЗаказ { get; set; }
        public virtual TbТовары TbТовары { get; set; }
    }
}
