//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_project_ver_5.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbТовары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbТовары()
        {
            this.TbСтрокиЗаказа = new HashSet<TbСтрокиЗаказа>();
        }
    
        public int Код_товара { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public decimal Цена { get; set; }
        public int Категория { get; set; }
        public string Путь_фото { get; set; }
    
        public virtual TbКатегории TbКатегории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbСтрокиЗаказа> TbСтрокиЗаказа { get; set; }
    }
}
